port = 5432
print_db_statistics = true

max_connections = 100
max_locks_per_transaction = 64
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,client=%h %r (%x:%e)'
log_level = 'ERROR'
logging_collector = 'on'

[superuser]
name = 'admin'
password = 'admin'

# options for hot standby
[replication]
name = 'replication'
password = 'replication'
# note: lag_health_threshold is in bytes - default to 10MB
# raise this on very high write rate installations
lag_health_threshold = 10240
enable = false
