version: '3'

services:
  pg1:
    image: irvingpop/postgresql11
    command: --group cluster
      --topology leader
  pg2:
    image: irvingpop/postgresql11
    command: --group cluster
      --topology leader
      --peer pg1
  pg3:
    image: irvingpop/postgresql11
    command: --group cluster
      --topology leader
      --peer pg1
  pgpool:
    image: irvingpop/pgpool-ii
    command:
      --peer pg1
      --bind database:postgresql.cluster

# volumes:
#   pg1-data:
#   pg2-data:
#   pg3-data:
